{{- if .Values.ingress.enabled -}}
{{- $fullName := include "irecruitBackendApp.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $serviceName := .Values.service.name -}}
{{- $servicePort := .Values.service.targetPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
    helm.sh/chart: {{ include "irecruitBackendApp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/rewrite-target": "/$1"
    "nginx.ingress.kubernetes.io/ssl-redirect": "false"
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
	{{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
	{{- end }}
{{- end }}
